# Generated by Django 6.1.1 on 2026-10-02 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('veiculo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('km', models.IntegerField()),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='recebido', max_length=20)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
