# Generated by Django 6.1.1 on 2026-10-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='foto_frente',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='foto_lat_dir',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='foto_lat_esq',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='foto_tras',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='letra_vidro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
