# Generated by Django 6.1.1 on 2026-10-02 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_atendimento_foto_frente_atendimento_foto_lat_dir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Detalhe', max_length=100)),
                ('imagem', models.ImageField(upload_to='veiculos/extras/')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_extras', to='core.atendimento')),
            ],
        ),
    ]
