# Generated by Django 6.1.1 on 2026-10-04 22:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fotoatendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
